### ISSUE TITLE
Stack outside of range error

### ISSUE THREAD

**Issue by 7Soul** [ISSOtm/gb-starter-kit#4]
Running into this error when I run Make:

`rgbasm -p 0xFF -isrc/ -isrc/include/ -Wall -Wextra -h -o obj/build_date.o src/res/build_date.asm
rgblink -p 0xFF -m bin/boilerplate.map -n bin/boilerplate.sym -o bin/boilerplate.gb obj/sgb.o obj/header.o obj/vectors.o obj/misc.o obj/crash_handler.o obj/unpb16.o obj/intro.o obj/build_date.o \
&& rgbfix -v -p 0xFF -v -i "BOIL" -k "HB" -l 0x33 -m 0x00 -n 0 -r 0x00 -t BOILERPLATE bin/boilerplate.gb
warning: Section "Stack"'s fixed address 0xdfc0 is outside of range [0xc000; 0xcfff]
warning: Section "Stack"'s end address 0xe000 is greater than last address 0xd000
error: Sanity checks failed
make: *** [Makefile:97: bin/boilerplate.gb] Error 1`

I haven't touched any of the files, this is right after I did a 'git clone "repo link" --recursive'. Both includes are there, and make clean doesn't help. RGBDS is v 0.4.0

**Comment by JL2210** [comment]
TBF, there is a comment right here:
https://github.com/JL2210/gb-starter-kit/blob/add68b4b9ecade42dc8f1cee150b0133af2304ce/src/header.asm#L147-L149
