### ISSUE TITLE
Invoking crash handler in header.asm without any note about it

### ISSUE THREAD

**Issue by JL2210** [ISSOtm/gb-starter-kit#5]
https://github.com/ISSOtm/gb-starter-kit/blob/add68b4b9ecade42dc8f1cee150b0133af2304ce/src/header.asm#L107

This isn't newbie-friendly; there's no mention of needing to remove this line before starting work, and any ROMs built will immediately crash.

I see 3 reasonable solutions to this problem:
* remove the line
* move the line to intro.asm with a comment saying to remove it
* add a comment saying to remove the line

**Comment by ISSOtm** [comment]
Fixed by #6
